### ISSUE TITLE
Set or update value for counter

### ISSUE THREAD

**Issue by danieldotnl** [danieldotnl/ha-measureit#115]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

For example: I want to count how many cups of coffee I brew with my coffee machine, so I know when it needs maintenance. However, the MeasureIt counter starts at 0 while I know I had already 200 cups of coffee. I want the MeasureIt counter to start at this value.
I should also be able to update the counter if Home Assistant was down and missed some cups.

### Describe the solution you'd like

Add a service like the utility_meter has to calibrate the counter sensors, or consider extending the reset service with a value field.

### Describe alternatives you've considered

Add the start value in the config flow. However, this does not enable one to update the value later on.

### Additional context

https://community.home-assistant.io/t/measureit-measure-all-you-need-based-on-time-and-templates/660614/26?u=danieldotnl

**Comment by nicknol** [comment]
works perfectly for my coffee counter! :)

**Comment by danieldotnl** [comment]
Solved in v0.8.0.
