### ISSUE TITLE
Time tracking gives me incorrect values

### ISSUE THREAD

**Issue by Damrak2022** [danieldotnl/ha-measureit#141]
Hello,
sorry for using Google Translate, but unfortunately my English is not that good anymore.
I suspect that I made a mistake in the configuration of Measurit, because the times are not correct for me.
All of my devices are connected to Shelly Plug S and are almost always on. I record the devices connected to it via the increased power consumption. So if the power consumption is higher than a value I have defined, the device is switched on and the time should be counted until the consumption falls below the value again. Then the time recording should end.
I have now switched on my air conditioning unit several times for 5 minutes and then checked Measurit. I expected 5 minutes there, but it showed 37 minutes.
I am attaching the code of my configuration and would be happy if you could tell me what I am doing wrong.

`{% if float(states.sensor.shelly_klimageraet_switch_0_power.state) > 20%}
  on
{%else%}
  off
{%endif%}`

Best regards, Andy

**Comment by danieldotnl** [comment]
I'm a bit confused by the percentage in your expression. What is the unit of measurement of your power sensor?
Anyway, the condition should look something like this: ```{{ states('sensor.shelly_klimageraet_switch_0_power') | float > 20 }} ```

PS: Please use the community forum for these kind of support questions.

**Comment by Damrak2022** [comment]
The sensor's unit of measurement is watts, but I only want to measure the time the device connected to it is switched on. So I think something is wrong in my configuration.

**Comment by danieldotnl** [comment]
And what is your definition of 'on'? Is that when it pull more than 20 watts of power? In that case the condition I gave above should work for you.

**Comment by Damrak2022** [comment]
Yes, thats right. Okay Thank you
