### ISSUE TITLE
Count down time sensors

### ISSUE THREAD

**Issue by Eckart0** [danieldotnl/ha-measureit#155]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Another suggestion: a service timer.
Is it possible to integrate a counter that counts down from a predefined time - for example, to trigger messages after the maintenance interval of a device has expired?

### Describe alternatives you've considered

.

### Additional context

.

**Comment by danieldotnl** [comment]
Hi, I'm not sure if I fully understand what you mean. So we have time sensors in MeasureIt that count up. Would you like to see those with a start value to count down from? 
But then how is this related to services as you titled your request 'service timer'?

**Comment by Eckart0** [comment]
Sorry for the late reply.

Yes, the idea is the option for a timer that counts down the switch-on times of an entity from a predefined time and that can also go into minus values - and thus measures maintenance intervals that have been exceeded. 

For all appliances that require regular maintenance - coffee machines, extractor fans, pool filters - this could be a simple basis for automation and notifications.

Best regards, Eckart

**Comment by danieldotnl** [comment]
I believe you can already achieve this (albeit a bit more advanced) by using a value_template. 
Something like:
`{{ 100000 - value }}`

Here 100000 is your service time in seconds.
Not sure at the moment if I want to make the MeasureIt config more complicated by adding a start value to count down from.
And your feature request didn't receive an +1s from others, so I close it for now.
