### ISSUE TITLE
Correction of incorrect data points (as with the statistics tool)

### ISSUE THREAD

**Issue by rudibarani** [danieldotnl/ha-measureit#176]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I encounter occasional errors in my modbus-derived data. This leads to big spikes e.g. when calculating the annual performance factor for our heat pump. It is usually around 4.5, but jumped above a million before adding a filter to the input data. It would be great if I could correct values like these to get correct data from MeasureIt, but I did not find an option in the statistics tab of the HA developer tools. 

![Bildschirmfoto 2024-09-02 um 11 33 34](https://github.com/user-attachments/assets/a4a34cdb-6506-46b4-8793-0e88a3914aed)

### Describe the solution you'd like

An easy to use option from the end-user perspective would be to be able to use said statistics tool for corrections.

### Describe alternatives you've considered

I have added a filter to the input-data of variables that I know might get false data. A solution for older data points and unexpected errors would be helptful.

### Additional context

If I misunderstood the way MeasureIt works and corrections in the input data are picked up in the MeasureIt entities after some time, please let me know.

**Comment by danieldotnl** [comment]
MeasureIt is indeed keeping its own state and not looking back at the corrected values of source sensors.
However, there is `calibrate` service which you could use to correct the state of Measureit.
