### ISSUE TITLE
V.Minor - Version number not updated in the config screen under 'Devices & Services' 

### ISSUE THREAD

**Issue by eon123** [danieldotnl/ha-measureit#186]
### System Health details

N/A

### Checklist

- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Currently shows 0.5.0
![image](https://github.com/user-attachments/assets/db37c5ae-cc8d-4d7f-b413-696e716c027a)

### Reproduction steps

1. Enter HA Settings > Devices & Services > MeasureIt landing page
2. Note version number under logo, doesn't match the entry in the HACS menu

### Debug logs

```text
N/A
```

**Comment by danieldotnl** [comment]
Thanks for reporting. HACS shows the github release version and HA shows the version that's in the integration manifest. I don't really care for the latter but I can see how it's confusing to the user. 
Will look for some way to automatically update the manifest based on the github release. Probably others figured this out already.
