### ISSUE TITLE
Reset with service

### ISSUE THREAD

**Issue by sheminasalam** [danieldotnl/ha-measureit#51]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Now there is predetermined intervals for the sensor to reset like days, month, year. But can there be an option where there is no prefixed interval but a service to reset the sensors?

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by danieldotnl** [comment]
You checked the box: 'This only contains 1 feature request', but you requested 2 features. Please create a separate request.

**Comment by danieldotnl** [comment]
Could you elaborate a little bit on your use cases?

**Comment by sheminasalam** [comment]
> Could you elaborate a little bit on your use cases?

I have some DIY battery operated door sensor. I want to count the number of open and close operations till the battery lasts. In the present state of this sensor, I can only set the reset with the preset intervals of days, hours, years etc. But in this case I need the option to reset the sensor when the battery drains fully and replaced with a new battery.

**Comment by redparchel** [comment]
I have a similar use case but for tracking how long my laundry has been running, and then reset the sensor via a service once it's complete. so it will count the next load of laundry independently from the previous

**Comment by danieldotnl** [comment]
The reset service is now available in v0.5.4!
