### ISSUE TITLE
Retain or not option for sensor

### ISSUE THREAD

**Issue by sheminasalam** [danieldotnl/ha-measureit#53]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Can there be an another option to select either to retain the sensor value or reset after reboot of HA?

I want to collect the number of times a sensor has changed from the time HA rebooted while I also have to continue the count of state changes even after reboot till the reset condition comes.

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by danieldotnl** [comment]
The v0.5.4 comes with a reset service. You could create an automation that triggers on startup and resets your sensor.

**Comment by danieldotnl** [comment]
I don't think that is possible because the template needs to become false before it can become true and be counted again.
What is your real life use case?

**Comment by sheminasalam** [comment]
> I don't think that is possible because the template needs to become false before it can become true and be counted again. What is your real life use case?

I have some battery powered door and window sensors. I count how many times the sensor detects open or close between battery replacements.

**Comment by danieldotnl** [comment]
What about just measuring when it closes and multiplying the counter value by 2? It's pretty obvious that it was opened as well before that, I would say?

**Comment by sheminasalam** [comment]
It would be possible but then again I would have to make one more template sensor for that.

**Comment by danieldotnl** [comment]
Another wild untested idea:
Create a counter template that checks if the state of your entity is open/closed and the last changed datetime is > 10 seconds ago. 
So after 10 seconds the template should become false until the state changes again.
