### ISSUE TITLE
Add a non-resetting sensor

### ISSUE THREAD

**Issue by rrozema** [danieldotnl/ha-measureit#56]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I like my statistics to be non-resetting or ever-increasing, so I can always query the statistic value for any randomly selected period by simply subtracting the start value from the end value, giving the change over the period. I often use the energy date range picker card this.

### Describe the solution you'd like

Please add another checkbox on the add sensors configuration page that allows to create a non-resetting sensor.

### Describe alternatives you've considered

I currently selected a yearly-resetting sensor as this is the longest period I could select, but this means that when selecting a period that includes a year change, the end value will be less than the start value, resulting in a negative change value for that period.

### Additional context

![image](https://github.com/danieldotnl/ha-measureit/assets/1747982/014776e4-c850-4315-b3ff-7a6b5e82297b)

**Comment by danieldotnl** [comment]
Fixed in v0.1.1!
I added an option 'forever (or service-operated). The service-operated part still needs to be implemented.
