### ISSUE TITLE
Daily Reset Using UTC Instead of Local Time

### ISSUE THREAD

**Issue by sigrist** [danieldotnl/ha-measureit#58]
## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.33.0
Stage | running
Available Repositories | 1380
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 22.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Samba share (12.2.0), Terminal & SSH (9.8.1), Node-RED (17.0.2), InfluxDB (5.0.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.1-1), JupyterLab (0.13.0), ESPHome (2023.12.6), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 8
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 6, 2024 at 6:13 PM
-- | --
current_recorder_run | January 15, 2024 at 3:17 PM
estimated_db_size | 992.92 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 5 / 5
local_online | 5 / 5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I've noticed that the script resets based on UTC time rather than the local time configured in Home Assistant. This leads to inaccurate daily measurements for users in different time zones. It would be more appropriate if the script could reset according to the local time settings of Home Assistant to ensure accurate daily tracking.

### Reproduction steps

1. Set your Home Assistant time zone to a non-UTC zone (e.g., `America/Sao_Paulo`).
2. Configure a measurement item with the following settings: From Time: 12:00:00 AM, Till Time: 12:00:00 AM.
3. Observe that the measurement resets at 9 PM instead of midnight, indicating that the reset is occurring based on UTC time rather than the local time set in Home Assistant.

Notice **Next reset** is 9PM
![image](https://github.com/danieldotnl/ha-measureit/assets/5570009/59b3209f-94e4-47e0-ad76-44d6acb7e797)

### Debug logs

```text
No logs
```

**Comment by danieldotnl** [comment]
Thank you for reporting this important issue! I've been testing this behavior fanatically, but yet you found an issue. 😐
I traced it back to the sensor data being restored from disk after a reboot.
After creating a new MeasureIt configure and before a reboot, the next reset datetine looks fine  to me.
Will continue looking for a solution asap when I find time.

**Comment by Seedser** [comment]
I noticed this UTC issue also. 
Great integration!

**Comment by tkirchbaum** [comment]
Mine is doing this as well. Any update on a fix?

**Comment by danieldotnl** [comment]
Yes, spending every free hour I have on a redesign that fixes this issue and much more.

**Comment by danieldotnl** [comment]
Fixed in v0.5.4!

**Comment by Roving-Ronin** [comment]
@danieldotnl Hi Daniel,  any chance you could add 'Discussions' to your REPO? Would be handy to have some How-To / Examples / General Chat areas in there, to allow those type threads to remain in there and not end up needing to open an 'issue'. TIA.

PS. Any updated doco for the new version with examples?

**Comment by danieldotnl** [comment]
Quite off-topic for this issue 😊

But I think I prefer to have those discussions on the community forum, rather than on github where it's much harder to find.
I also hope that people will share their use cases on the forum to inspire others and help them with the config.

**Comment by mikenhu** [comment]
Hi, the reset time is now stuck at 12AM no matter what the setting is. I tried deleting and recreating the sensor but no success.

**Comment by danieldotnl** [comment]
Could you elaborate a bit on that? What kind of period do you choose and what do you expect instead of 12 midnight?

**Comment by mikenhu** [comment]
My setting for the sensor is from 6pm to next day's 6pm as you can see below.
![image](https://github.com/danieldotnl/ha-measureit/assets/9059129/6dbbce28-7f32-42b6-907f-4572f5f251f1)
But the sensor itself still shows the reset time is at the default 12am.
![image](https://github.com/danieldotnl/ha-measureit/assets/9059129/1017a105-89bc-48e4-b346-247ecfae3754)

**Comment by danieldotnl** [comment]
Ah I see what you are trying to do. But sensors always reset at midnight (except for the hourly sensors). The time you configured is the time when the sensor will measure. E.g. if you configure from 12pm - 6pm, it would still reset at midnight but only measure your afternoon naps :)
But I can see that it's not convenient to reset a time-in-bed sensor at midnight. Best option for you I think (for now), is to create a sensor that does not reset automatically and then create an automation to call the reset service at 6 PM.

**Comment by mikenhu** [comment]
when I set this sensor up it does not have any field that says it'd always reset at midnight. And I don't think it is very intuitive to have the sensors always automatically reset at midnight, while it's configured to measure between selected times.

**Comment by danieldotnl** [comment]
Thanks, I'll then try to better clarify in the description the difference between when the sensor is measuring and when it is resetting.

**Comment by mikenhu** [comment]
Hi, for some reason, I tried to recreate the time sensor with different measurement time e.g. 6PM to 9PM, but the sensor still shows reset time from 12AM. This still happens after I updated to the latest version 0.6.0
<img width="423" alt="Screenshot 2024-03-17 at 09 29 38" src="https://github.com/danieldotnl/ha-measureit/assets/9059129/fca0b36d-0cb9-4610-94c1-f0c00744ecbb">
<img width="565" alt="Screenshot 2024-03-17 at 09 29 50" src="https://github.com/danieldotnl/ha-measureit/assets/9059129/f9d5bd74-8d91-4c60-aea2-7fef0e183653">

**Comment by danieldotnl** [comment]
@mikenhu I created a feature request for your issue: #102 
Will close this one.
