### ISSUE TITLE
Can't edit a sensor configuration

### ISSUE THREAD

**Issue by shlomki** [danieldotnl/ha-measureit#87]
### System Health details

Not really relevant here

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After creating a new sensor
If I wish to edit the reset period, it's not really possible because no other options are available.

### Reproduction steps

1. Create a new source sensor
2. Choose any time you wish
3. Choose period = forever
4. Complete the process
5. Click configure on the new sensor you're created
6. Choose "Edit a Sensor Configuration"
**Expected Result:**
All of the period options are available for selection
**Actual Result:**
Only "forever" is available for selection

![image](https://github.com/danieldotnl/ha-measureit/assets/34508546/42f863ba-d7be-4091-a2bc-908307b92f91)

### Debug logs

```text
I don't think this is relevant but let me know if you'd like me to add logs.
```

**Comment by danieldotnl** [comment]
It is indeed not possible to edit the reset period afterwards because it messes up the calculations and the period is also part of the name of the sensor. Instead create a new one and delete the old one.
